### ISSUE TITLE
没加载 prerender-spa-plugin

### ISSUE THREAD

**Issue by xianweics** [deboyblog/vue-prerender-demo#1]
为什么你这个项目没加载 prerender-spa-plugin？

**Comment by deboyblog** [comment]
我并不是用这种插件的方式解决SEO的哦 
请结合我这篇文章: [Prerender + vuejs SEO最佳实践 百度爬虫 + 谷歌收录 亲测成功](https://www.deboy.cn/prerender-vuejs1-X-SEO-best-practice.html)

**Comment by xianweics** [comment]
好的，谢谢了
